name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright

      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      - name: Run Playwright tests
        run: |
          python main.py

      - name: Upload coverage reports to Canyon
        run: |
          ls .canyon_output/*.json
          curl -LOs https://github.com/canyon-project/uploader/releases/download/v0.0.1/uploader
          chmod +x uploader
          ./uploader

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
